# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170811_0658'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='activation_key_exprires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
