# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-23 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170817_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_key',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_key_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
