# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(error_messages={'unique': 'A Party with that name already exists'}, max_length=50, unique=True)),
                ('name', models.CharField(error_messages={'unique': 'A Party with that name already exists'}, max_length=200, unique=True)),
            ],
        ),
    ]
