# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='votes', through='wp_core.VoteQuestion', to='wp_core.Userprofile'),
        ),
        migrations.AlterField(
            model_name='votequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wp_core.Userprofile'),
        ),
    ]
