# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp_party', '0001_initial'),
        ('wp_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wp_party.Party'),
        ),
    ]
