# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0002_answer_party'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='closed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
