# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-18 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0002_auto_20170509_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='votes',
            field=models.ManyToManyField(related_name='votes', through='wp_core.VoteQuestion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='votequestion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
