# Generated by Django 3.2.4 on 2021-07-19 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0003_auto_20170831_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voteanswer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='votequestion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
