# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 17:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0003_auto_20170518_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Userprofile',
        ),
    ]
