# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0004_auto_20170522_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='votequestion',
            name='up',
            field=models.BooleanField(default=True),
        ),
    ]
