# Generated by Django 3.2.5 on 2021-08-18 21:30

from django.conf import settings
from django.db import migrations, models
import wp_core.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wp_core', '0004_auto_20210719_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(wp_core.models.get_staff_backup_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(wp_core.models.get_staff_backup_user), to=settings.AUTH_USER_MODEL),
        ),
    ]
