# Generated by Django 3.2.5 on 2021-08-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wp_core', '0005_auto_20210818_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='closed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
